import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/others/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Karel Vaněk",
    template: "%s | Karel Vaněk"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="cs">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
